variable "vpc_cidr" {}
variable "pub_sbn_1a_cidr" {}
variable "pub_sbn_1b_cidr" {}
variable "pub_sbn_1c_cidr" {}
variable "pvt_sbn_1a_cidr" {}
variable "pvt_sbn_1b_cidr" {}
variable "pvt_sbn_1c_cidr" {}
variable "ec2_ami" {}
variable "ec2_ins_type" {}
variable "ec2_count" {}
variable "ec2_key_name" {}
variable "ec2_ami_profile" {}
variable "ec2_associate_public_ip_address" {}
variable "ec2_tag_name" {}
variable "ec2_tag_vpc" {}
variable "ec2_tag_purpose" {}
variable "ec2_sg_name" {}
variable "ec2_sg_ing_cidr" {}
variable "ec2_sg_tag_name" {}
variable "ec2_sg_tag_vpc" {}
variable "ec2_sg_tag_purpose" {}
variable "vpc_tag_name" {}
variable "vpc_tag_vpc" {}
variable "vpc_tag_purpose" {}
variable "nat_tag_name" {}
variable "nat_tag_vpc" {}
variable "nat_tag_purpose" {}
variable "pub_tbl_tag_name" {}
variable "pub_tbl_tag_vpc" {}
variable "pub_tbl_tag_purpose" {}
variable "pvt_tbl_tag_name" {}
variable "pvt_tbl_tag_vpc" {}
variable "pvt_tbl_tag_purpose" {}
variable "igw_tag_name" {}
variable "igw_tag_vpc" {}
variable "igw_tag_purpose" {}
variable "elb_name" {}
variable "elb_tag_name" {}
variable "elb_tag_vpc" {}
variable "elb_tag_purpose" {}
variable "elb_sg_name" {}
variable "elb_sg_http_ing_cidr" {}
variable "elb_sg_tag_name" {}
variable "elb_sg_tag_vpc" {}
variable "elb_sg_tag_purpose" {}

variable "rds_sg_name" {}
variable "rds_sg_tag_name" {}
variable "rds_sg_tag_vpc" {}
variable "rds_sg_tag_purpose" {}

variable "rds_username" {}
variable "rds_password" {}
variable "rds_name" {}
variable "rds_multi_az" {}
variable "rds_allocated_storage" {}
variable "rds_instance_class" {}
variable "rds_storage_type" {}
variable "rds_param_grp_name" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_publicly_accessible" {}
variable "rds_sbn_grp_name" {}
variable "rds_skip_final_snapshot" {}
variable "rds_apply_immediately" {}
variable "rds_join_buffer_size" {}
variable "rds_log_bin_trust_function_creators" {}
variable "rds_log_output" {}
variable "rds_log_queries_not_using_indexes" {}
variable "rds_long_query_time" {}
variable "rds_max_allowed_packet" {}
variable "rds_max_connections" {}
variable "rds_slow_query_log" {}
variable "rds_sql_mode" {}
variable "rds_time_zone" {}
variable "rds_tag_name" {}
variable "rds_tag_vpc" {}
variable "rds_tag_purpose" {}
variable "rds_allow_major_version_upgrade" {}
variable "rds_auto_minor_version_upgrade" {}
variable "rds_maintenance_window" {}
variable "rds_copy_tags_to_snapshot" {}
variable "rds_backup_retention_period" {}
variable "rds_backup_window" {}
variable "rds_sg_cnc_ing_cidr" {}
variable "vpc_to_peer" {}
variable "peer_route_table" {}
variable "vpc_to_route_cidr" {}